name: Build & Deploy
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_PACKAGE_PATH: src\MultiFamilyPortal/publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: src\MultiFamilyPortal
  MultiFamilyPortalProfile: ${{ secrets.multifamilyportal_5677 }}
  StageLibertasEquitiesProfile: ${{ secrets.libertasequities_stage_1cb4 }}

jobs:
  build-and-deploy:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - AZURE_WEBAPP_NAME: multifamilyportal
            AZURE_WEBAPP_PUBLISH_PROFILE: ${{ env.MultiFamilyPortalProfile }}
          - AZURE_WEBAPP_NAME: libertasequities
            AZURE_WEBAPP_PUBLISH_PROFILE: ${{ env.StageLibertasEquitiesProfile }}
            AZURE_WEBAPP_SLOT_NAME: stage
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: NuGet Restore
      run: |
        dotnet nuget add source ${{ secrets.IN_HOUSE_NUGET_FEED }} --name InHouse --username ${{ secrets.IN_HOUSE_NUGET_USER }} --password ${{ secrets.IN_HOUSE_API_KEY }}
        dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ matrix.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ matrix.AZURE_WEBAPP_PUBLISH_PROFILE }}
        slot-name: ${{ matrix.AZURE_WEBAPP_SLOT_NAME }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
